cognitive-complexity-threshold = 20
too-many-arguments-threshold = 5
type-complexity-threshold = 250
single-char-binding-names-threshold = 4
too-many-lines-threshold = 100
trivial-copy-size-limit = 16
enum-variant-name-threshold = 3
enum-variant-size-threshold = 200
verbose-bit-mask-threshold = 1
literal-representation-threshold = 16